type Product = {
  Id: string;
  OwnerId: string;
  IsDeleted: boolean;
  Name: string;
  CreatedDate: string;
  CreatedById: string;
  LastModifiedDate: string;
  LastModifiedById: string;
  SystemModstamp: string;
  LastViewedDate: string | null;
  LastReferencedDate: string | null;
  ConnectionReceivedId: string | null;
  ConnectionSentId: string | null;
  Artikel__c: string;
  Datum_aanmaken__c: string | null;
  Fabrikantscode__c: string | null;
  Merk__c: string;
  Prijs__c: number | null;
  Prijs_incl_heffingen__c: number;
  Productnaam__c: string;
  Produktindeling__c: string | null;
  Status__c: string | null;
  Stibat__c: string | null;
  Thuiskopie__c: string | null;
  UNSPSC_code__c: string | null;
  Verwijderingsbijdrage__c: string | null;
  Voorraad__c: number;
  Supplier__c: string | null;
  zonder_wijziging__c: number;
  Active__c: boolean;
  Sales_Price__c: number;
  EAN__c: string | null;
  SupplierId__c: string;
  category__c: string;
  description__c: string | null;
  Unique_Id__c: string;
};
